language: node_js
node_js:
- '4.0'
branches:
  except:
  - releases
env:
  global:
  - GIT_AUTHOR_EMAIL: branch-release-bot@users.noreply.github.com
  - GIT_AUTHOR_NAME: BranchReleaseDemoBot
  - secure: NjrdIuGn7UHIGz6OHfanKNJQWHX5bUSh3B7cgG8jOOccShZegnrARP1vDQLgn2g6v+zpiXruGabTmNgDNO2d5T0Bdh2yWKFlo1riqGUsE+23aVBm3j2W6Z5nKdt1ULFoyYxjlhabbbLHU6ufDeabNDWJAVavxPRDJex+3RFhXjrXAAe6o9kLYgWsUN2IBba9xG6+Wuu/F11T8o5QpPvjoBunyIDfCtN+A0dAT9OnFb7gRdN8souvUPqY1Mj+D7/D1sElLgdHAzpMPj213bMGOxF1Z2ufrRUKkoQ7l2pcvWpw7U8LLwyFIsIq5g2MtHDiXl3SvIhhXE3jSVpNAryxqX1L4weJY7mgXr8hlmfvyJihn1rFsNq6r8c41wVJr81gbh6TxXNuSq9I4bHr48GoDPvWm89fxF8ok5Wr8G73s0Feg95iDtTfQVuHNvws23+iaxFHdIO0cjezCI+pj+rzT9AIh+Y2SGDpUdlWidDODpuP9PKgyrliT4M80Jrbi2twf26CyuCJGiwsKyhvXwBQ1gc0cnAg93KVbHllwnWkDdPTMp+cjLkO2CAUs6HhARVgI85+CtExbveiJNg29M1zmNte9QlwmPL5/kVt21Q6nhIQjCK92u9RM0z5+wJZmOvk1LbIezo9wemDYCZ1YqPl06JqewxxQxYUjQHEjktREs0=
deploy:
  skip_cleanup: true
  provider: script
  script: npm run release-to-branch
  on:
    branch: master
