language: node_js
node_js:
- '4.0'
branches:
  except:
  - releases
env:
  global:
  - secure: jk1UvqyJ4TrrY6CVsAVwK5w57NYHnNZlmaWw8sHp61CM0QFshcfQbRkQETlAWrGijmuOQfUwBtvoc5Te61IGPOK8W/65h0TbJmSC1q8zDyH1nnGaSquAOQeg/ql7L7R95WCGk68C/QMLwcNcQsnvfwR04yWJSo9AkjWs8uJJHK9DvLGT5OTk84vS69pthQI4AhOTHipNIjHOLn/iaDWb2ZzIFijgOHkx8ljYwlLQXDht6/bxTcnTuFSz+vFckDsTYHVQuHGv/idHDk3BPLmSRwv/Vq6sA/ilFmJK9agwBqe0uAYgGMSzKXDjiOMbo4VsRICGz6rqEPoGZ6xiHji00H77Kjccih1PnM5nb3HLxrRHgTsH8AmcPC8MVQPX7FmEGe43SIpG1SKoLbuNkSNGMXoJDN0vGrD7NZd2rCkbS1YvX4opv3JBUiiHOLdrRQgRdWV6O8+6N6v3E2mlI7LlfQeansU3PIKvNsdmbtmITCGjNP2cjk2D/7ZVH6PTG2w1JoPbfFLpqKtVUB60/M+aSZklz/Kc0uKMjTY/07k2QG8cQ6cTyogTPa24aIMytKpJlMY2q77KDoSO/aLx1j6pL9WltpqfBOFGPSwMxjIbP8fSBO7peBfnhOYOy8tQPyMIpRdwRZdQziPqyMMrxitAbV8e1l54hiIKNP43K4rcy8s=
  - GIT_AUTHOR_EMAIL: branch-release-bot@users.noreply.github.com
  - GIT_AUTHOR_NAME: BranchReleaseDemoBot
deploy:
  skip_cleanup: true
  provider: script
  script: npm run release-to-branch
  on:
    branch: master
